es2lad = {
    "cero": "sero",
    "un": "un",
    "uno" : "uno",
    "dos" : "dos",
    "tres" : "tres ",
    "cuatro" : "kuatro",
    "cinco" : "sinko",
    "seis" : "sesh",
    "siete" : "siete",
    "ocho" : "ocho ",
    "nueve" : "mueve",
    "diez" : "diez",
    "once" : "onze ",
    "doce" : "dodje",
    "trece" : "tredje",
    "catorce" : "katorze",
    "quince" : "kinze",
    "dieciséis" : "diisesh",
    "diecisiete" : "diisiete",
    "dieciocho" : "diziocho",
    "diecinueve" : "dizimueve",
    "veinte" : "vente",
    "veintiún" : "ventiuno",
    "veintidós" : "ventidos",
    "veintitrés" : "ventitres",
    "veinticuatro" : "ventikuatro",
    "veinticinco" : "ventisinko",
    "veintiséis" : "ventisesh",
    "veintisiete" : "ventisiete",
    "veintiocho" : "ventiocho",
    "veintinueve" : "ventimueve",
    "treinta" : "trenta",
    "treinta y un" : "trentiuno",
    "treinta y dos" : "trentidos",
    "treinta y tres" : "trentitres",
    "treinta y cuatro" : "trentikuatro",
    "treinta y cinco" : "trentisinko",
    "treinta y seis" : "trentisesh",
    "treinta y siete" : "trentisiete",
    "treinta y ocho" : "trentiocho",
    "treinta y nueve" : "trentimueve",
    "cuarenta" : "kuarenta",
    "cuarenta y un" : "kuarenta i uno",
    "cuarenta y dos" : "kuarenta i dos",
    "cuarenta y tres" : "kuarenta i tres",
    "cincuenta" : "sinkuenta",
    "cincuenta y cuatro" : "sinkuenta i kuatro",
    "cincuenta y cinco" : "sinkuenta i sinko",
    "cincuenta y seis" : "sinkuenta i sesh",
    "cincuenta y siete" : "sinkuenta i siete",
    "cincuenta y ocho" : "sinkuenta i ocho",
    "sesenta" : "sesenta",
    "sesenta y nueve" : "sesenta i mueve",
    "setenta" : "setenta",
    "setenta y un" : "setenta i uno",
    "setenta y dos" : "setenta i dos",
    "ochenta" : "ochenta",
    "ochenta y tres" : "ochenta i tres",
    "ochenta y cuatro" : "ochenta i kuatro",
    "ochenta y cinco" : "ochenta i sinko",
    "noventa" : "noventa",
    "noventa y seis" : "noventa i sesh",
    "noventa y siete" : "noventa i siete",
    "noventa y ocho" : "noventa i ocho",
    "noventa y nueve" : "noventa i mueve",
    "cien" : "sien",
    "cien un" : "sien i uno",
    "cien dos" : "sien i dos",
    "cien diez" : "sien i diez",
    "cien noventa" : "sien i noventa",
    "doscientos" : "dozientos",
    "doscientos un" : "dozientos i uno",
    "trescientos" : "trezientos",
    "cuatrocientos" : "kuatroshentos",
    "cincocientos" : "kinyentos",
    "seiscientos" : "sheshentos",
    "sietecientos" : "setesientos",
    "ochocientos" : "ochosientos",
    "novecientos" : "novesientos",
    "mil" : "mil",
    "millar": "mil",
    "y": "i"
}
